language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
  - "pypy-5.3.1"
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - libssl1.0.0
install:
  - python setup.py install
script: python setup.py test
